// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: services/user_mgmt/proto/response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_OK                  ResponseCode = 0
	ResponseCode_INVALID_QUERY       ResponseCode = 1
	ResponseCode_INVALID_FIELD_NAME  ResponseCode = 2
	ResponseCode_INTERNAL_ERROR      ResponseCode = 3
	ResponseCode_INVALID_SCHEMA      ResponseCode = 4
	ResponseCode_USER_ALREADY_EXISTS ResponseCode = 5
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "OK",
		1: "INVALID_QUERY",
		2: "INVALID_FIELD_NAME",
		3: "INTERNAL_ERROR",
		4: "INVALID_SCHEMA",
		5: "USER_ALREADY_EXISTS",
	}
	ResponseCode_value = map[string]int32{
		"OK":                  0,
		"INVALID_QUERY":       1,
		"INVALID_FIELD_NAME":  2,
		"INTERNAL_ERROR":      3,
		"INVALID_SCHEMA":      4,
		"USER_ALREADY_EXISTS": 5,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_services_user_mgmt_proto_response_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_services_user_mgmt_proto_response_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_services_user_mgmt_proto_response_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code ResponseCode `protobuf:"varint,2,opt,name=code,proto3,enum=blend.services.user_mgmt.proto.ResponseCode" json:"code,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Response_FetchId
	//	*Response_CreateUser
	Data   isResponse_Data `protobuf_oneof:"data"`
	Errors []*Error        `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_mgmt_proto_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_mgmt_proto_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_services_user_mgmt_proto_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_OK
}

func (m *Response) GetData() isResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Response) GetFetchId() *FetchIdResponse {
	if x, ok := x.GetData().(*Response_FetchId); ok {
		return x.FetchId
	}
	return nil
}

func (x *Response) GetCreateUser() *CreateUserResponse {
	if x, ok := x.GetData().(*Response_CreateUser); ok {
		return x.CreateUser
	}
	return nil
}

func (x *Response) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_FetchId struct {
	FetchId *FetchIdResponse `protobuf:"bytes,3,opt,name=fetch_id,json=fetchId,proto3,oneof"`
}

type Response_CreateUser struct {
	CreateUser *CreateUserResponse `protobuf:"bytes,4,opt,name=create_user,json=createUser,proto3,oneof"`
}

func (*Response_FetchId) isResponse_Data() {}

func (*Response_CreateUser) isResponse_Data() {}

type FetchIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchIdResponse) Reset() {
	*x = FetchIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_mgmt_proto_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchIdResponse) ProtoMessage() {}

func (x *FetchIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_mgmt_proto_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchIdResponse.ProtoReflect.Descriptor instead.
func (*FetchIdResponse) Descriptor() ([]byte, []int) {
	return file_services_user_mgmt_proto_response_proto_rawDescGZIP(), []int{1}
}

func (x *FetchIdResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_user_mgmt_proto_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_mgmt_proto_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_services_user_mgmt_proto_response_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_services_user_mgmt_proto_response_proto protoreflect.FileDescriptor

var file_services_user_mgmt_proto_response_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x62, 0x6c, 0x65, 0x6e, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc8, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x40, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x62, 0x6c, 0x65,
	0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x4c,
	0x0a, 0x08, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x66, 0x65, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x55, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0f, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x2a, 0x82, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44,
	0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0x04, 0x12,
	0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x05, 0x42, 0x24, 0x5a, 0x22, 0x62, 0x6c, 0x65, 0x6e,
	0x64, 0x77, 0x69, 0x74, 0x68, 0x2e, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_user_mgmt_proto_response_proto_rawDescOnce sync.Once
	file_services_user_mgmt_proto_response_proto_rawDescData = file_services_user_mgmt_proto_response_proto_rawDesc
)

func file_services_user_mgmt_proto_response_proto_rawDescGZIP() []byte {
	file_services_user_mgmt_proto_response_proto_rawDescOnce.Do(func() {
		file_services_user_mgmt_proto_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_user_mgmt_proto_response_proto_rawDescData)
	})
	return file_services_user_mgmt_proto_response_proto_rawDescData
}

var file_services_user_mgmt_proto_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_user_mgmt_proto_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_user_mgmt_proto_response_proto_goTypes = []interface{}{
	(ResponseCode)(0),          // 0: blend.services.user_mgmt.proto.ResponseCode
	(*Response)(nil),           // 1: blend.services.user_mgmt.proto.Response
	(*FetchIdResponse)(nil),    // 2: blend.services.user_mgmt.proto.FetchIdResponse
	(*CreateUserResponse)(nil), // 3: blend.services.user_mgmt.proto.CreateUserResponse
	(*Error)(nil),              // 4: blend.services.user_mgmt.proto.Error
}
var file_services_user_mgmt_proto_response_proto_depIdxs = []int32{
	0, // 0: blend.services.user_mgmt.proto.Response.code:type_name -> blend.services.user_mgmt.proto.ResponseCode
	2, // 1: blend.services.user_mgmt.proto.Response.fetch_id:type_name -> blend.services.user_mgmt.proto.FetchIdResponse
	3, // 2: blend.services.user_mgmt.proto.Response.create_user:type_name -> blend.services.user_mgmt.proto.CreateUserResponse
	4, // 3: blend.services.user_mgmt.proto.Response.errors:type_name -> blend.services.user_mgmt.proto.Error
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_user_mgmt_proto_response_proto_init() }
func file_services_user_mgmt_proto_response_proto_init() {
	if File_services_user_mgmt_proto_response_proto != nil {
		return
	}
	file_services_user_mgmt_proto_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_user_mgmt_proto_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_mgmt_proto_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_user_mgmt_proto_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_user_mgmt_proto_response_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Response_FetchId)(nil),
		(*Response_CreateUser)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_user_mgmt_proto_response_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_user_mgmt_proto_response_proto_goTypes,
		DependencyIndexes: file_services_user_mgmt_proto_response_proto_depIdxs,
		EnumInfos:         file_services_user_mgmt_proto_response_proto_enumTypes,
		MessageInfos:      file_services_user_mgmt_proto_response_proto_msgTypes,
	}.Build()
	File_services_user_mgmt_proto_response_proto = out.File
	file_services_user_mgmt_proto_response_proto_rawDesc = nil
	file_services_user_mgmt_proto_response_proto_goTypes = nil
	file_services_user_mgmt_proto_response_proto_depIdxs = nil
}
