// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/actions.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_CODE_OK                   StatusCode = 0
	StatusCode_STATUS_CODE_INTERNAL_ERROR       StatusCode = 1
	StatusCode_STATUS_CODE_INVALID_NUMBER       StatusCode = 2
	StatusCode_STATUS_CODE_NUMBER_ALREADY_TAKEN StatusCode = 3
	StatusCode_STATUS_CODE_UID_ALREADY_TAKEN    StatusCode = 4
	StatusCode_STATUS_CODE_INVALID_UID          StatusCode = 5
	StatusCode_STATUS_CODE_INVALID_ACTION       StatusCode = 6
	StatusCode_STATUS_CODE_TXN_NOT_FOUND        StatusCode = 7
	StatusCode_STATUS_CODE_INVALID_OTP          StatusCode = 8
	StatusCode_STATUS_CODE_OTP_MISSING          StatusCode = 9
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_CODE_OK",
		1: "STATUS_CODE_INTERNAL_ERROR",
		2: "STATUS_CODE_INVALID_NUMBER",
		3: "STATUS_CODE_NUMBER_ALREADY_TAKEN",
		4: "STATUS_CODE_UID_ALREADY_TAKEN",
		5: "STATUS_CODE_INVALID_UID",
		6: "STATUS_CODE_INVALID_ACTION",
		7: "STATUS_CODE_TXN_NOT_FOUND",
		8: "STATUS_CODE_INVALID_OTP",
		9: "STATUS_CODE_OTP_MISSING",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_OK":                   0,
		"STATUS_CODE_INTERNAL_ERROR":       1,
		"STATUS_CODE_INVALID_NUMBER":       2,
		"STATUS_CODE_NUMBER_ALREADY_TAKEN": 3,
		"STATUS_CODE_UID_ALREADY_TAKEN":    4,
		"STATUS_CODE_INVALID_UID":          5,
		"STATUS_CODE_INVALID_ACTION":       6,
		"STATUS_CODE_TXN_NOT_FOUND":        7,
		"STATUS_CODE_INVALID_OTP":          8,
		"STATUS_CODE_OTP_MISSING":          9,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_actions_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_actions_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{0}
}

type Action3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Action3Request) Reset() {
	*x = Action3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action3Request) ProtoMessage() {}

func (x *Action3Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action3Request.ProtoReflect.Descriptor instead.
func (*Action3Request) Descriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{0}
}

func (x *Action3Request) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Action3Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=blend.services.user_creation.proto.StatusCode" json:"code,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Response_Action_1
	Data isResponse_Data `protobuf_oneof:"data"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_OK
}

func (m *Response) GetData() isResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Response) GetAction_1() *Action1Response {
	if x, ok := x.GetData().(*Response_Action_1); ok {
		return x.Action_1
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_Action_1 struct {
	Action_1 *Action1Response `protobuf:"bytes,3,opt,name=action_1,json=action1,proto3,oneof"`
}

func (*Response_Action_1) isResponse_Data() {}

type Action1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId string `protobuf:"bytes,1,opt,name=txnId,proto3" json:"txnId,omitempty"`
	Otp   string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *Action1Response) Reset() {
	*x = Action1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action1Response) ProtoMessage() {}

func (x *Action1Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action1Response.ProtoReflect.Descriptor instead.
func (*Action1Response) Descriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{2}
}

func (x *Action1Response) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *Action1Response) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

var File_proto_actions_proto protoreflect.FileDescriptor

var file_proto_actions_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x42, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e,
	0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x50, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39,
	0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x2a, 0xbf, 0x02, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x55, 0x4d, 0x42,
	0x45, 0x52, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e,
	0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x55, 0x49, 0x44, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x54, 0x41,
	0x4b, 0x45, 0x4e, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x49, 0x44,
	0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x06, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x54, 0x58, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x07, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4f, 0x54, 0x50, 0x10, 0x08, 0x12, 0x1b,
	0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f, 0x54,
	0x50, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x09, 0x42, 0x2c, 0x5a, 0x2a, 0x62,
	0x6c, 0x65, 0x6e, 0x64, 0x77, 0x69, 0x74, 0x68, 0x2e, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_actions_proto_rawDescOnce sync.Once
	file_proto_actions_proto_rawDescData = file_proto_actions_proto_rawDesc
)

func file_proto_actions_proto_rawDescGZIP() []byte {
	file_proto_actions_proto_rawDescOnce.Do(func() {
		file_proto_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_actions_proto_rawDescData)
	})
	return file_proto_actions_proto_rawDescData
}

var file_proto_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_actions_proto_goTypes = []interface{}{
	(StatusCode)(0),         // 0: blend.services.user_creation.proto.StatusCode
	(*Action3Request)(nil),  // 1: blend.services.user_creation.proto.Action3Request
	(*Response)(nil),        // 2: blend.services.user_creation.proto.Response
	(*Action1Response)(nil), // 3: blend.services.user_creation.proto.Action1Response
}
var file_proto_actions_proto_depIdxs = []int32{
	0, // 0: blend.services.user_creation.proto.Response.code:type_name -> blend.services.user_creation.proto.StatusCode
	3, // 1: blend.services.user_creation.proto.Response.action_1:type_name -> blend.services.user_creation.proto.Action1Response
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_actions_proto_init() }
func file_proto_actions_proto_init() {
	if File_proto_actions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_actions_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Response_Action_1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_actions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_actions_proto_goTypes,
		DependencyIndexes: file_proto_actions_proto_depIdxs,
		EnumInfos:         file_proto_actions_proto_enumTypes,
		MessageInfos:      file_proto_actions_proto_msgTypes,
	}.Build()
	File_proto_actions_proto = out.File
	file_proto_actions_proto_rawDesc = nil
	file_proto_actions_proto_goTypes = nil
	file_proto_actions_proto_depIdxs = nil
}
