// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/actions.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_OK                        StatusCode = 0
	StatusCode_STATUS_CODE_INTERNAL_ERROR       StatusCode = 1
	StatusCode_STATUS_CODE_INVALID_NUMBER       StatusCode = 2
	StatusCode_STATUS_CODE_NUMBER_ALREADY_TAKEN StatusCode = 3
	StatusCode_STATUS_CODE_UID_ALREADY_TAKEN    StatusCode = 4
	StatusCode_STATUS_CODE_INVALID_UID          StatusCode = 5
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "STATUS_OK",
		1: "STATUS_CODE_INTERNAL_ERROR",
		2: "STATUS_CODE_INVALID_NUMBER",
		3: "STATUS_CODE_NUMBER_ALREADY_TAKEN",
		4: "STATUS_CODE_UID_ALREADY_TAKEN",
		5: "STATUS_CODE_INVALID_UID",
	}
	StatusCode_value = map[string]int32{
		"STATUS_OK":                        0,
		"STATUS_CODE_INTERNAL_ERROR":       1,
		"STATUS_CODE_INVALID_NUMBER":       2,
		"STATUS_CODE_NUMBER_ALREADY_TAKEN": 3,
		"STATUS_CODE_UID_ALREADY_TAKEN":    4,
		"STATUS_CODE_INVALID_UID":          5,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_actions_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_proto_actions_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{0}
}

type Action1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=blend.services.user_creation.proto.StatusCode" json:"code,omitempty"`
}

func (x *Action1Response) Reset() {
	*x = Action1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action1Response) ProtoMessage() {}

func (x *Action1Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action1Response.ProtoReflect.Descriptor instead.
func (*Action1Response) Descriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{0}
}

func (x *Action1Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Action1Response) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_OK
}

type Action2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=blend.services.user_creation.proto.StatusCode" json:"code,omitempty"`
}

func (x *Action2Response) Reset() {
	*x = Action2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action2Response) ProtoMessage() {}

func (x *Action2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action2Response.ProtoReflect.Descriptor instead.
func (*Action2Response) Descriptor() ([]byte, []int) {
	return file_proto_actions_proto_rawDescGZIP(), []int{1}
}

func (x *Action2Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Action2Response) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_OK
}

var File_proto_actions_proto protoreflect.FileDescriptor

var file_proto_actions_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x42, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x62, 0x6c, 0x65,
	0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x65, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x42, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2e, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0xc1, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4e, 0x55, 0x4d,
	0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x5f, 0x41, 0x4c, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x49, 0x44, 0x5f, 0x41,
	0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x04, 0x12, 0x1b,
	0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x55, 0x49, 0x44, 0x10, 0x05, 0x42, 0x2c, 0x5a, 0x2a, 0x62,
	0x6c, 0x65, 0x6e, 0x64, 0x77, 0x69, 0x74, 0x68, 0x2e, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_actions_proto_rawDescOnce sync.Once
	file_proto_actions_proto_rawDescData = file_proto_actions_proto_rawDesc
)

func file_proto_actions_proto_rawDescGZIP() []byte {
	file_proto_actions_proto_rawDescOnce.Do(func() {
		file_proto_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_actions_proto_rawDescData)
	})
	return file_proto_actions_proto_rawDescData
}

var file_proto_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_actions_proto_goTypes = []interface{}{
	(StatusCode)(0),         // 0: blend.services.user_creation.proto.StatusCode
	(*Action1Response)(nil), // 1: blend.services.user_creation.proto.Action1Response
	(*Action2Response)(nil), // 2: blend.services.user_creation.proto.Action2Response
}
var file_proto_actions_proto_depIdxs = []int32{
	0, // 0: blend.services.user_creation.proto.Action1Response.code:type_name -> blend.services.user_creation.proto.StatusCode
	0, // 1: blend.services.user_creation.proto.Action2Response.code:type_name -> blend.services.user_creation.proto.StatusCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_actions_proto_init() }
func file_proto_actions_proto_init() {
	if File_proto_actions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_actions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_actions_proto_goTypes,
		DependencyIndexes: file_proto_actions_proto_depIdxs,
		EnumInfos:         file_proto_actions_proto_enumTypes,
		MessageInfos:      file_proto_actions_proto_msgTypes,
	}.Build()
	File_proto_actions_proto = out.File
	file_proto_actions_proto_rawDesc = nil
	file_proto_actions_proto_goTypes = nil
	file_proto_actions_proto_depIdxs = nil
}
