// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/stages.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageType int32

const (
	StageType_STAGE_1 StageType = 0
	StageType_STAGE_2 StageType = 1
	StageType_STAGE_3 StageType = 2
	StageType_STAGE_4 StageType = 3
)

// Enum value maps for StageType.
var (
	StageType_name = map[int32]string{
		0: "STAGE_1",
		1: "STAGE_2",
		2: "STAGE_3",
		3: "STAGE_4",
	}
	StageType_value = map[string]int32{
		"STAGE_1": 0,
		"STAGE_2": 1,
		"STAGE_3": 2,
		"STAGE_4": 3,
	}
)

func (x StageType) Enum() *StageType {
	p := new(StageType)
	*p = x
	return p
}

func (x StageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stages_proto_enumTypes[0].Descriptor()
}

func (StageType) Type() protoreflect.EnumType {
	return &file_proto_stages_proto_enumTypes[0]
}

func (x StageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageType.Descriptor instead.
func (StageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stages_proto_rawDescGZIP(), []int{0}
}

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage StageType `protobuf:"varint,1,opt,name=stage,proto3,enum=blend.services.user_creation.proto.StageType" json:"stage,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Stage_Stage_1
	//	*Stage_Stage_2
	//	*Stage_Stage_3
	Data isStage_Data `protobuf_oneof:"data"`
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_proto_stages_proto_rawDescGZIP(), []int{0}
}

func (x *Stage) GetStage() StageType {
	if x != nil {
		return x.Stage
	}
	return StageType_STAGE_1
}

func (m *Stage) GetData() isStage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Stage) GetStage_1() *Stage1 {
	if x, ok := x.GetData().(*Stage_Stage_1); ok {
		return x.Stage_1
	}
	return nil
}

func (x *Stage) GetStage_2() *Stage3 {
	if x, ok := x.GetData().(*Stage_Stage_2); ok {
		return x.Stage_2
	}
	return nil
}

func (x *Stage) GetStage_3() *Stage4 {
	if x, ok := x.GetData().(*Stage_Stage_3); ok {
		return x.Stage_3
	}
	return nil
}

type isStage_Data interface {
	isStage_Data()
}

type Stage_Stage_1 struct {
	Stage_1 *Stage1 `protobuf:"bytes,2,opt,name=stage_1,json=stage1,proto3,oneof"`
}

type Stage_Stage_2 struct {
	Stage_2 *Stage3 `protobuf:"bytes,3,opt,name=stage_2,json=stage2,proto3,oneof"`
}

type Stage_Stage_3 struct {
	Stage_3 *Stage4 `protobuf:"bytes,4,opt,name=stage_3,json=stage3,proto3,oneof"`
}

func (*Stage_Stage_1) isStage_Data() {}

func (*Stage_Stage_2) isStage_Data() {}

func (*Stage_Stage_3) isStage_Data() {}

type Stage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *Stage1) Reset() {
	*x = Stage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage1) ProtoMessage() {}

func (x *Stage1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage1.ProtoReflect.Descriptor instead.
func (*Stage1) Descriptor() ([]byte, []int) {
	return file_proto_stages_proto_rawDescGZIP(), []int{1}
}

func (x *Stage1) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Stage1) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Stage3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Stage3) Reset() {
	*x = Stage3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage3) ProtoMessage() {}

func (x *Stage3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage3.ProtoReflect.Descriptor instead.
func (*Stage3) Descriptor() ([]byte, []int) {
	return file_proto_stages_proto_rawDescGZIP(), []int{2}
}

func (x *Stage3) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Stage3) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type Stage4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Email  string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Stage4) Reset() {
	*x = Stage4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage4) ProtoMessage() {}

func (x *Stage4) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage4.ProtoReflect.Descriptor instead.
func (*Stage4) Descriptor() ([]byte, []int) {
	return file_proto_stages_proto_rawDescGZIP(), []int{3}
}

func (x *Stage4) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Stage4) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Stage4) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_stages_proto protoreflect.FileDescriptor

var file_proto_stages_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x43, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2d, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x45, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x31, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x67, 0x65, 0x31, 0x12, 0x45,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x33, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x32, 0x12, 0x45, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x33,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x34, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x67, 0x65, 0x33, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x31, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x32,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x48, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x34, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2a, 0x3f, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41,
	0x47, 0x45, 0x5f, 0x31, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f,
	0x32, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x33, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x47, 0x45, 0x5f, 0x34, 0x10, 0x03, 0x42, 0x2c, 0x5a,
	0x2a, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x77, 0x69, 0x74, 0x68, 0x2e, 0x6d, 0x65, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_stages_proto_rawDescOnce sync.Once
	file_proto_stages_proto_rawDescData = file_proto_stages_proto_rawDesc
)

func file_proto_stages_proto_rawDescGZIP() []byte {
	file_proto_stages_proto_rawDescOnce.Do(func() {
		file_proto_stages_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stages_proto_rawDescData)
	})
	return file_proto_stages_proto_rawDescData
}

var file_proto_stages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_stages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_stages_proto_goTypes = []interface{}{
	(StageType)(0), // 0: blend.services.user_creation.proto.StageType
	(*Stage)(nil),  // 1: blend.services.user_creation.proto.Stage
	(*Stage1)(nil), // 2: blend.services.user_creation.proto.Stage1
	(*Stage3)(nil), // 3: blend.services.user_creation.proto.Stage3
	(*Stage4)(nil), // 4: blend.services.user_creation.proto.Stage4
}
var file_proto_stages_proto_depIdxs = []int32{
	0, // 0: blend.services.user_creation.proto.Stage.stage:type_name -> blend.services.user_creation.proto.StageType
	2, // 1: blend.services.user_creation.proto.Stage.stage_1:type_name -> blend.services.user_creation.proto.Stage1
	3, // 2: blend.services.user_creation.proto.Stage.stage_2:type_name -> blend.services.user_creation.proto.Stage3
	4, // 3: blend.services.user_creation.proto.Stage.stage_3:type_name -> blend.services.user_creation.proto.Stage4
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_stages_proto_init() }
func file_proto_stages_proto_init() {
	if File_proto_stages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_stages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Stage_Stage_1)(nil),
		(*Stage_Stage_2)(nil),
		(*Stage_Stage_3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stages_proto_goTypes,
		DependencyIndexes: file_proto_stages_proto_depIdxs,
		EnumInfos:         file_proto_stages_proto_enumTypes,
		MessageInfos:      file_proto_stages_proto_msgTypes,
	}.Build()
	File_proto_stages_proto = out.File
	file_proto_stages_proto_rawDesc = nil
	file_proto_stages_proto_goTypes = nil
	file_proto_stages_proto_depIdxs = nil
}
